### ISSUE TITLE
Lack of fonts for Asian language?

### ISSUE THREAD

**Issue by jfcherng** [masemoel/device_xiaomi_picasso_recovery_deprecated#7]
After changing the language to `Chinese (Traditional)`, it looks like the following screenshot.

![Screenshot_PBRP_2020-09-22-23-09-41](https://user-images.githubusercontent.com/6594915/93901333-00f89900-fd29-11ea-99d9-4b55c382cf23.png)

I also tried `Janpanese` and it was suffering from the same issue.

Sorry if I file this issue in a wrong repo.

**Comment by masemoel** [comment]
Hello @jfcherng 
You are using PBRP, right?

**Comment by jfcherng** [comment]
Sure. To be more specific, `PBRP-picasso-3.0.0-20200914-1146-UNOFFICIAL_ANDROID10.zip` with `xiaomi.eu_multi_HMK305G_20.8.13_v12-10.zip`.

**Comment by masemoel** [comment]
I have asked to the PBRP team and they tell me that this has been already fixed and will be available with the 3.0.1 release, very soon.
I will bring-up a new release whenever the v3.0.1 is published (so it will contain the language issue).
By the way, you can make a screenshot in recovery with the same key combination as we use in Android (power and volume -).

**Comment by jfcherng** [comment]
Thanks for that information and your work! And the screenshot technique works :+1: I've updated the original post.

**Comment by masemoel** [comment]
Hello again @jfcherng 
I've just released a new PBRP release with lots of fixes from the team (you can download it here https://github.com/Redmi-K30-5G/device_xiaomi_picasso_recovery/releases/tag/PBRP , remember that this repository is deprecated and follow this new one from now on).
I set some Asian languages and now all seem to be translated and showed 100% correctly.

**Comment by jfcherng** [comment]
> Hello again @jfcherng
> I've just released a new PBRP release with lots of fixes from the team (you can download it here [Redmi-K30-5G/device_xiaomi_picasso_recovery@`PBRP` (release)](https://github.com/Redmi-K30-5G/device_xiaomi_picasso_recovery/releases/tag/PBRP) , remember that this repository is deprecated and follow this new one from now on).
> I set some Asian languages and now all seem to be translated and showed 100% correctly.

Thanks. I have watched that repo on GitHub so won't miss a release :+1:
